# Generated by Django 4.2.21 on 2025-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='descuento_global',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='empleado_ventas',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalledocumento',
            name='total_moneda_extranjera',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='descuento_global',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='empleado_ventas',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notacredito',
            name='descuento_global',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='empleado_ventas',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notadebito',
            name='descuento_global',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='notadebito',
            name='empleado_ventas',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='concepto_detraccion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='correlativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='monto_detraccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='porcentaje_detraccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='serie_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='tipo_base_imponible',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='concepto_detraccion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='correlativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_detraccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='porcentaje_detraccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='serie_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_base_imponible',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='concepto_detraccion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='correlativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='monto_detraccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='porcentaje_detraccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='serie_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='tipo_base_imponible',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='concepto_detraccion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='correlativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='monto_detraccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='porcentaje_detraccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='serie_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='tipo_base_imponible',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
