# Generated by Django 4.2.21 on 2025-06-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_boleta_descuento_global_boleta_empleado_ventas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecha_contabilizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha_documento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha_vencimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_contabilizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_documento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='fecha_contabilizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='fecha_documento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='fecha_vencimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='fecha_contabilizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='fecha_documento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='fecha_vencimiento',
            field=models.DateTimeField(),
        ),
    ]
