# Generated by Django 4.2.21 on 2025-06-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_boleta_referencia_factura_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='aplica_auto_detraccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='aplica_detraccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='solo_impuesto',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='aplica_auto_detraccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='aplica_detraccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='aplica_auto_detraccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='aplica_detraccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='aplica_auto_detraccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='aplica_detraccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
