# Generated by Django 4.2.21 on 2025-06-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_alter_boleta_aplica_auto_detraccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='tipo_base_imponible',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_base_imponible',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='tipo_base_imponible',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='tipo_base_imponible',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
