# Generated by Django 4.2.21 on 2025-06-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_alter_boleta_fecha_contabilizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='tipo_documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='tipo_documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='tipo_documento',
            field=models.CharField(max_length=20),
        ),
    ]
