# Generated by Django 4.2.21 on 2025-06-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_alter_boleta_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='tipo_documento',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='tipo_operacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_documento',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_operacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='tipo_documento',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='tipo_operacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='tipo_documento',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='tipo_operacion',
            field=models.CharField(max_length=50),
        ),
    ]
