# Generated by Django 4.2.21 on 2025-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_alter_boleta_tipo_operacion_fe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='condicion_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='condicion_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='condicion_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='condicion_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
