# Generated by Django 4.2.21 on 2025-07-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_alter_boleta_condicion_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='descripcion_migracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='estado_migracion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('migrado', 'Migrado'), ('error_migracion', 'Error de migración')], default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='factura',
            name='descripcion_migracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado_migracion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('migrado', 'Migrado'), ('error_migracion', 'Error de migración')], default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='descripcion_migracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='estado_migracion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('migrado', 'Migrado'), ('error_migracion', 'Error de migración')], default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='notadebito',
            name='descripcion_migracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notadebito',
            name='estado_migracion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('migrado', 'Migrado'), ('error_migracion', 'Error de migración')], default='pendiente', max_length=50),
        ),
    ]
