# Generated by Django 4.2.21 on 2025-06-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_alter_boleta_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='tipo_operacion_fe',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_operacion_fe',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='tipo_operacion_fe',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='tipo_operacion_fe',
            field=models.CharField(max_length=50),
        ),
    ]
