# Generated by Django 4.2.21 on 2025-08-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_boleta_descripcion_migracion_boleta_estado_migracion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellidos',
            new_name='nombres_apellidos',
        ),
        migrations.RenameField(
            model_name='propietario',
            old_name='apellidos',
            new_name='nombres_apellidos',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='nombres',
        ),
        migrations.AlterField(
            model_name='boleta',
            name='condicion_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.condicionpago'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='cuenta_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='empleado_ventas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.empleado'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.propietario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='codigo_empleado',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='condicion_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.condicionpago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cuenta_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='empleado_ventas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.empleado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.propietario'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='condicion_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.condicionpago'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='cuenta_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='empleado_ventas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.empleado'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.propietario'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='condicion_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.condicionpago'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='cuenta_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='empleado_ventas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.empleado'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.propietario'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='codigo_propietario',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
