# Generated by Django 4.2.21 on 2025-06-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_alter_boleta_operacion_detraccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocumento',
            name='tipo_afectacion_igv',
            field=models.CharField(max_length=50),
        ),
    ]
