# Generated by Django 4.2.21 on 2025-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_alter_detalledocumento_tipo_afectacion_igv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocumento',
            name='grupo_detraccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
